---
- name: Sync Pull task - Executed on destination host {{ servidor_destino }}
  hosts: all
  gather_facts: false
  vars:
    #ansible_python_interpreter: /usr/bin/python3.9
    ansible_python_interpreter: /usr/bin/python2.6
  tasks:
    - name: Preparing {{ ruta_origen }} file to be transferred.
      ansible.builtin.stat:
        path: "{{ ruta_origen }}"
      register: filestatus

    - fail:
        msg: The object to be transferred WAS NOT FOUND.
      when: not filestatus.stat.exists

    - fail:
        msg: The object to be transferred SHOULD BE A FILE.
      when: filestatus.stat.isdir

    - name: Transferring file from {{ servidor_origen }} to {{ servidor_destino }} using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ ruta_origen }}"
        dest: "{{ ruta_destino }}"
        mode: pull
      delegate_to: "{{ servidor_destino }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3.6
        ansible_ssh_password: "123456"
      register: syncfile
      when: filestatus.stat.isreg and filestatus.stat.exists is defined
      
    - name: Debug syncfile
      debug:
        msg: "{{ syncfile.changed }}"
