---
- name: AlmaLinux Server Ansible Playbook Execution
  hosts: all
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: "{{ source_directory_path }}"/"{{ file_name }}"
        dest: "{{ destination_directory_path }}"/
        mode: pull
      delegate_to: "{{ destination_server }}"
        
