---
- name: Sync Push task - Executed on source host "{{ servidor_destino }}"
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Check if the file exists
      ansible.builtin.stat:
        path: "{{ ruta_origen }}"
      register: filestatus
  
    - name: Ansible copy the file from "{{ servidor_origen }}" to "{{ servidor_destino }}" using Method Push
      tags: sync-push
      synchronize:
        src: "{{ ruta_origen }}"
        dest: "{{ ruta_destino }}"
        mode: push
      delegate_to: "{{ servidor_destino }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3.9
      register: syncfile
      when: filestatus.stat.exists
      
    - name: Debug syncfile
      debug:
        msg: "{{ syncfile.changed }}"
