---
- name: AlmaLinux Server Ansible Playbook Execution
  hosts: all
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Transfer file from ServerA to ServerB
      environment:
        RSYNC_PASSWORD: "{{ destination_user_password }}"
      ansible.posix.synchronize:
        mode: pull
        ##src: "{{ source_path }}"
        src: rsync://"{{ destination_user }}"@"{{ source_server }}":"{{ source_path }}"
        dest: "{{ destination_path }}"
        ##dest: rsync://"{{ destination_user }}"@"{{ destination_server }}":"{{ destination_path }}"
      delegate_to: "{{ destination_server }}"
      #when: file_to_check.stat.exists is defined and file_to_check.stat.exists
