---
- name: Sync Pull task - Executed on destination host {{ servidor_destino }}
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Preparing {{ ruta_origen }} file to be transferred.
      ansible.builtin.stat:
        path: "{{ ruta_origen }}"
      register: filestatus

    #- name: Check if {{ ruta_origen }} file exists.
    - fail:
        msg: The object to be transferred should be a file.
      when: filestatus.stat.isdir

    - name: Transferring file from {{ servidor_origen }} to {{ servidor_destino }} using Method Push
      tags: sync-pull
      synchronize:
        src: "{{ ruta_origen }}"
        dest: "{{ ruta_destino }}"
        mode: pull
      delegate_to: "{{ servidor_destino }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3.6
      register: syncfile
      when: filestatus.stat.exists is defined and filestatus.stat.isreg
      
    - name: Debug syncfile
      debug:
        msg: "{{ syncfile.changed }}"
