---
- name: AlmaLinux Server Ansible Playbook Execution
  hosts: all
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Check if the file exists
      ansible.builtin.stat:
        path: "{{ source_path }}"
      register: file_to_check

    - name: Task name
      debug:
        msg: "The file or file exists"
      when: file_to_check.stat.exists is defined and file_to_check.stat.exists

    - name: Transfer file from ServerA to ServerB
      environment:
        RSYNC_PASSWORD: "{{ destination_user_password }}"
      ansible.posix.synchronize:
        mode: pull
        ##src: "{{ source_path }}"
        src: rsync://"{{ destination_user }}"@"{{ destination_server }}":"{{ destination_path }}"
        dest: "{{ destination_path }}"
        ##dest: rsync://"{{ destination_user }}"@"{{ destination_server }}":"{{ destination_path }}"
      ##delegate_to: "{{ destination_server }}"
      #when: file_to_check.stat.exists is defined and file_to_check.stat.exists
