---
- name: Sync Pull task - Executed on destination host "{{ servidor_destino }}"
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ binario_python }}"
  tasks:
    - name: Transferring file from "{{ servidor_origen }}" to "{{ servidor_destino }}" using method pull
      tags: sync-pull
      #synchronize:
      ansible.posix.synchronize:
        src: "{{ ruta_origen }}/{{ item }}"
        dest: "{{ ruta_destino }}"
        mode: pull
      delegate_to: "{{ servidor_destino }}"
      register: syncfile
      vars:
        ansible_python_interpreter: "{{ ruta_python }}"
      with_items:
        - "{{ nombre_archivo }}"
      
    - name: Debug syncfile, changed?
      debug:
        msg: "{{ syncfile.changed }}"
