---
- name: Sync Push task - Executed on destination host {{ servidor_origen }}
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ ruta_python }}"
  tasks:
    - name: Transferring file from {{ servidor_origen }} to {{ servidor_destino }} using method push
      tags: sync-push
      #synchronize:
      ansible.posix.synchronize:
        src: "{{ ruta_origen }}/{{ item }}"
        dest: "{{ ruta_destino }}"
        mode: push
      delegate_to: "{{ servidor_origen }}"
      register: syncfile
      vars:
        ansible_python_interpreter: "{{ ruta_python }}"
      with_items:
        - "{{ nombre_archivo }}"
      
    - name: Debug syncfile, changed?
      debug:
        msg: "{{ syncfile.changed }}"
